basic:
    name: zawia3.com
    environments:
        production: 'https://zawia3.com'
        staging: 'https://dev.zawia3.com/'
        development: ''
    basicAuth:
        staging: { user: dev.zawia3.com, password: oT4Pao$p }
    breakpoints:
        - 320
        - 768
        - 1440
    pages:
        - /
        - /category/investigation
        - /category/op-ed
        - /category/society
        - /category/economics
        - /category/politics
        - /category/rights
        - /category/culture
        - /en
        - /new-years-budget
        - /2025/06/19
        - /social-housing
        - /2025/06/17
        - /egypt-gas
        - /2025/06/16
        - /cairo-gaza
        - /2025/06/12
        - /egyptian-pilgrims
        - /2025/06/09
        - /gaz
        - /2025/06/11
        - /uae-suez-canal
        - /2025/05/23
        - /cbe
        - /2025/05/17
        - /denial-policy
        - /2025/06/10
        - /civil-movement-5
        - /2025/05/27
        - /the-deep-state
        - /2025/05/29
        - /opinion-article-torture
        - /2025/05/25
        - /egyptian-military-economy
        - /2025/05/28
        - /egypt-eid-al-adha
        - /2025/06/05
        - /culture
        - /el-fardous
        - /2025/05/20
        - /sudanese-refugee
        - /2025/06/02
        - /refugees
        - /2025/05/26
        - /editorial-policy
        - /about-us
    monitoring:
        days: {  }
        type: ''
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    delay: 10
    scroll: false
    headers: {  }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content: {  }
    sensitivity: 5
    night_mode: false
    retina_images: false
    single_ip: false
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
